services:
  postgres:
    image: postgres:17.0
    # ports:
    #   - "5432:5432"
    environment:
      POSTGRES_USER: ${POSTGRES_USER:-postgres}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD:-postgres}
      POSTGRES_DB: ${POSTGRES_DB:-pocketmoney_db}
    volumes:
      - postgres-data:/var/lib/postgresql/data
      - ./docker/db-init:/docker-entrypoint-initdb.d
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U ${POSTGRES_USER:-postgres}"]
      interval: 10s
      timeout: 5s
      retries: 5

  redis:
    image: redis:alpine3.20
    # ports:
    #   - "6379:6379"

  pocketmoney-api:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8383:8383"
    environment:
      SPRING_PROFILES_ACTIVE: ${SPRING_PROFILES_ACTIVE:-dev}
      SPRING_DATASOURCE_URL: jdbc:postgresql://postgres:5432/${POSTGRES_DB:-pocketmoney_db}
      SPRING_DATASOURCE_USERNAME: ${POSTGRES_USER:-postgres}
      SPRING_DATASOURCE_PASSWORD: ${POSTGRES_PASSWORD:-postgres}
    depends_on:
      postgres:
        condition: service_healthy

  ussd-service:
    build:
      context: ./ussd
      dockerfile: services/ussd-service/app.dockerfile
    ports:
      - "9000:9000"
    depends_on:
      postgres:
        condition: service_healthy
      redis:
        condition: service_started
      pocketmoney-api:
        condition: service_started

  pgadmin:
    image: elestio/pgadmin:latest
    ports:
      - "5050:80"
    environment:
      PGADMIN_DEFAULT_EMAIL: ${PGADMIN_DEFAULT_EMAIL:-admin@mopay.rw}
      PGADMIN_DEFAULT_PASSWORD: ${PGADMIN_DEFAULT_PASSWORD:-mopay12}
      PGADMIN_CONFIG_SERVER_MODE: "False"
      PGADMIN_CONFIG_WTF_CSRF_ENABLED: "False"
    depends_on:
      postgres:
        condition: service_healthy
    volumes:
      - ./docker/pgadmin/servers.json:/pgadmin4/servers.json
      - ./docker/pgadmin/pgpass:/pgadmin4/.pgpass
      - pgadmin-data:/var/lib/pgadmin

volumes:
  postgres-data:
  pgadmin-data:
