apiVersion: v1
kind: Service
metadata:
  annotations:
    kompose.cmd: kompose convert -f docker-compose-deployment.yml
    kompose.version: 1.34.0 (HEAD)
  labels:
    io.kompose.service: ussd-service
  name: ussd-service
spec:
  ports:
    - name: "9000"
      port: 9000
      targetPort: 9000
    - name: "50051"
      port: 50051
      targetPort: 50051
  selector:
    io.kompose.service: ussd-service
